run:
  timeout: 3m

linters:
  default: all
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - unused
    - gofmt
    - goimports

linters-settings:
  errcheck:
    ignore: ''